import { addIcons } from 'ionicons';
import {
  accessibilityOutline,
  addOutline,
  alertCircle,
  alertCircleOutline,
  analyticsOutline,
  barChartOutline,
  checkmarkCircle,
  checkmarkCircleOutline,
  chevronForwardOutline,
  closeOutline,
  cloudOfflineOutline,
  copyOutline,
  createOutline,
  cubeOutline,
  documentTextOutline,
  downloadOutline,
  fileTrayOutline,
  fileTrayStackedOutline,
  homeOutline,
  listOutline,
  logoWhatsapp,
  medkitOutline,
  peopleOutline,
  personCircleOutline,
  printOutline,
  pulseOutline,
  refreshOutline,
  scanOutline,
  searchOutline,
  settingsOutline,
  shareSocialOutline,
  shieldOutline,
  statsChartOutline,
  timeOutline,
  trashOutline,
} from 'ionicons/icons';

export function registerIcons(): void {
  addIcons({
    'accessibility-outline': accessibilityOutline,
    'add-outline': addOutline,
    'alert-circle': alertCircle,
    'alert-circle-outline': alertCircleOutline,
    'analytics-outline': analyticsOutline,
    'bar-chart-outline': barChartOutline,
    'checkmark-circle': checkmarkCircle,
    'checkmark-circle-outline': checkmarkCircleOutline,
    'chevron-forward-outline': chevronForwardOutline,
    'close-outline': closeOutline,
    'cloud-offline-outline': cloudOfflineOutline,
    'copy-outline': copyOutline,
    'create-outline': createOutline,
    'cube-outline': cubeOutline,
    'document-text-outline': documentTextOutline,
    'download-outline': downloadOutline,
    'file-tray-outline': fileTrayOutline,
    'file-tray-stacked-outline': fileTrayStackedOutline,
    'home-outline': homeOutline,
    'list-outline': listOutline,
    'logo-whatsapp': logoWhatsapp,
    'medkit-outline': medkitOutline,
    'people-outline': peopleOutline,
    'person-circle-outline': personCircleOutline,
    'print-outline': printOutline,
    'pulse-outline': pulseOutline,
    'refresh-outline': refreshOutline,
    'scan-outline': scanOutline,
    'search-outline': searchOutline,
    'settings-outline': settingsOutline,
    'share-social-outline': shareSocialOutline,
    'shield-outline': shieldOutline,
    'stats-chart-outline': statsChartOutline,
    'time-outline': timeOutline,
    'trash-outline': trashOutline,
  });
}
