import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateInitialSchema1741190810000 implements MigrationInterface {
  name = 'CreateInitialSchema1741190810000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "usuario" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "username" varchar(50) NOT NULL, "nombre" varchar(120) NOT NULL, "rol" varchar(20) NOT NULL, "pin_hash" varchar(255) NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "activo" boolean NOT NULL DEFAULT (1), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), created_by_id integer, CONSTRAINT "UQ_usuario_username" UNIQUE ("username"))`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "medicamento" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "nombre_generico" varchar(120) NOT NULL, "nombre_comercial" varchar(120), "presentacion" varchar(80) NOT NULL, "concentracion" float NOT NULL, "unidad_concentracion" varchar(10) NOT NULL DEFAULT ('mg'), "es_vital" boolean NOT NULL DEFAULT (0), "activo" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), created_by_id integer, updated_by_id integer)`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "paciente" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "id_emergencia" varchar(60) NOT NULL, "nombre" varchar(120) NOT NULL, "apellido" varchar(120) NOT NULL, "cedula" varchar(30), "telefono" varchar(20), "sexo" varchar(1) NOT NULL, "edad_estimada" integer NOT NULL, "fecha_nacimiento" varchar(10), "edad_manual" integer, "es_recien_nacido" boolean NOT NULL DEFAULT (0), "peso_estimado" float NOT NULL, "es_damnificado" boolean NOT NULL DEFAULT (0), "tiene_carga_familiar" boolean NOT NULL DEFAULT (0), "tiene_discapacidad_motora" boolean NOT NULL DEFAULT (0), "activo" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), situacion_vivienda varchar(20) NOT NULL DEFAULT 'no_afectado', updated_at datetime, created_by_id integer, updated_by_id integer)`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "lote" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "medicamento_id" integer NOT NULL, "codigo_qr" varchar(100) NOT NULL, "cantidad_inicial" integer NOT NULL, "cantidad_actual" integer NOT NULL, "fecha_vencimiento" date NOT NULL, "donante" varchar(120), "ubicacion" varchar(120), "activo" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_lote_medicamento" FOREIGN KEY ("medicamento_id") REFERENCES "medicamento" ("id") ON DELETE RESTRICT)`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "lote_movimiento" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "lote_id" integer NOT NULL, "tipo" varchar(20) NOT NULL, "cantidad" integer NOT NULL, "motivo" varchar(255), "usuario_id" integer, "activo" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_lote_movimiento_lote" FOREIGN KEY ("lote_id") REFERENCES "lote" ("id") ON DELETE CASCADE, CONSTRAINT "FK_lote_movimiento_usuario" FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") ON DELETE SET NULL)`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "catalogo_patologia" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "nombre" varchar(120) NOT NULL, "descripcion" varchar(255), "activo" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), updated_at datetime, created_by_id integer, updated_by_id integer)`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "catalogo_necesidad" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "nombre" varchar(120) NOT NULL, "descripcion" varchar(255), "activo" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), updated_at datetime, created_by_id integer, updated_by_id integer)`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "configuracion" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "medicamento_id" integer NOT NULL, "umbral_minimo" integer NOT NULL DEFAULT (10), "dosis_maxima_mg_kg" float NOT NULL DEFAULT (0), "peso_referencia_kg" float NOT NULL DEFAULT (70), "activo" boolean NOT NULL DEFAULT (1), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), created_at datetime, created_by_id integer, updated_by_id integer, CONSTRAINT "UQ_configuracion_medicamento" UNIQUE ("medicamento_id"), CONSTRAINT "FK_configuracion_medicamento" FOREIGN KEY ("medicamento_id") REFERENCES "medicamento" ("id") ON DELETE CASCADE)`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "dispensacion" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "paciente_id" integer NOT NULL, "usuario_id" integer NOT NULL, "fecha_hora" datetime NOT NULL, "observaciones" text, "receta_id" integer, "activo" boolean NOT NULL DEFAULT (1), CONSTRAINT "FK_dispensacion_paciente" FOREIGN KEY ("paciente_id") REFERENCES "paciente" ("id") ON DELETE RESTRICT, CONSTRAINT "FK_dispensacion_usuario" FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") ON DELETE RESTRICT, CONSTRAINT "FK_dispensacion_receta" FOREIGN KEY ("receta_id") REFERENCES "receta" ("id") ON DELETE SET NULL)`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "dispensacion_detalle" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "dispensacion_id" integer NOT NULL, "lote_id" integer NULL, "medicamento_id" integer NOT NULL, "cantidad" integer NOT NULL, "dosis_mg_kg" float NOT NULL DEFAULT (0), "activo" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), FOREIGN KEY ("dispensacion_id") REFERENCES "dispensacion"("id") ON DELETE CASCADE, FOREIGN KEY ("lote_id") REFERENCES "lote"("id") ON DELETE RESTRICT, FOREIGN KEY ("medicamento_id") REFERENCES "medicamento"("id") ON DELETE RESTRICT)`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "nucleo_familiar" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "codigo_carpa" varchar(20), "ubicacion" varchar(200), "activo" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "titular_id" integer, updated_at datetime, created_by_id integer, updated_by_id integer, CONSTRAINT "FK_nucleo_familiar_titular" FOREIGN KEY ("titular_id") REFERENCES "paciente" ("id") ON DELETE NO ACTION)`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "nucleo_familiar_miembro" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "nucleo_id" integer NOT NULL, "paciente_id" integer NOT NULL, "relacion" varchar(30) NOT NULL, "activo" boolean NOT NULL DEFAULT (1), created_by_id integer, CONSTRAINT "UQ_nucleo_familiar_miembro_paciente" UNIQUE ("paciente_id"), CONSTRAINT "FK_nucleo_familiar_miembro_nucleo" FOREIGN KEY ("nucleo_id") REFERENCES "nucleo_familiar" ("id") ON DELETE CASCADE, CONSTRAINT "FK_nucleo_familiar_miembro_paciente" FOREIGN KEY ("paciente_id") REFERENCES "paciente" ("id") ON DELETE NO ACTION)`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "receta" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "paciente_id" integer NOT NULL, "doctor_id" integer NOT NULL, "fecha_hora" datetime NOT NULL, "estado" varchar(20) NOT NULL DEFAULT ('pendiente'), "activo" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), motivo varchar(500), CONSTRAINT "FK_receta_paciente" FOREIGN KEY ("paciente_id") REFERENCES "paciente" ("id") ON DELETE RESTRICT, CONSTRAINT "FK_receta_doctor" FOREIGN KEY ("doctor_id") REFERENCES "usuario" ("id") ON DELETE RESTRICT)`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "receta_detalle" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "receta_id" integer NOT NULL, "medicamento_id" integer NOT NULL, "cantidad_recetada" integer NULL, "dias" integer NULL, "dosis_indicada" varchar(255) NULL, "activo" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), FOREIGN KEY ("receta_id") REFERENCES "receta"("id") ON DELETE CASCADE, FOREIGN KEY ("medicamento_id") REFERENCES "medicamento"("id") ON DELETE RESTRICT)`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "paciente_patologia" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "paciente_id" integer NOT NULL, "patologia_id" integer NOT NULL, "tratamiento" varchar(255), created_by_id integer, CONSTRAINT "FK_paciente_patologia_paciente" FOREIGN KEY ("paciente_id") REFERENCES "paciente" ("id") ON DELETE CASCADE, CONSTRAINT "FK_paciente_patologia_patologia" FOREIGN KEY ("patologia_id") REFERENCES "catalogo_patologia" ("id") ON DELETE CASCADE)`);

    await queryRunner.query(`CREATE TABLE IF NOT EXISTS "paciente_necesidad" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "paciente_id" integer NOT NULL, "necesidad_id" integer NOT NULL, "suplida" boolean NOT NULL DEFAULT (0), "fecha_suplida" datetime NULL, "suplida_por_id" integer NULL, "activo" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), created_by_id integer, CONSTRAINT "FK_paciente_necesidad_paciente" FOREIGN KEY ("paciente_id") REFERENCES "paciente" ("id") ON DELETE CASCADE, CONSTRAINT "FK_paciente_necesidad_necesidad" FOREIGN KEY ("necesidad_id") REFERENCES "catalogo_necesidad" ("id") ON DELETE CASCADE)`);
  }

  async down(_queryRunner: QueryRunner): Promise<void> {
    // No implementado
  }
}
